// @generated by protobuf-ts 2.11.1 with parameter force_optimize_code_size
// @generated from protobuf file "econ.proto" (syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message CEconItemPreviewDataBlock
 */
export interface CEconItemPreviewDataBlock {
    /**
     * @generated from protobuf field: optional uint32 accountid = 1
     */
    accountid?: number;
    /**
     * @generated from protobuf field: optional uint64 itemid = 2
     */
    itemid?: bigint;
    /**
     * @generated from protobuf field: optional uint32 defindex = 3
     */
    defindex?: number;
    /**
     * @generated from protobuf field: optional uint32 paintindex = 4
     */
    paintindex?: number;
    /**
     * @generated from protobuf field: optional uint32 rarity = 5
     */
    rarity?: number;
    /**
     * @generated from protobuf field: optional uint32 quality = 6
     */
    quality?: number;
    /**
     * @generated from protobuf field: optional uint32 paintwear = 7
     */
    paintwear?: number;
    /**
     * @generated from protobuf field: optional uint32 paintseed = 8
     */
    paintseed?: number;
    /**
     * @generated from protobuf field: optional uint32 killeaterscoretype = 9
     */
    killeaterscoretype?: number;
    /**
     * @generated from protobuf field: optional uint32 killeatervalue = 10
     */
    killeatervalue?: number;
    /**
     * @generated from protobuf field: optional string customname = 11
     */
    customname?: string;
    /**
     * @generated from protobuf field: repeated CEconItemPreviewDataBlock.Sticker stickers = 12
     */
    stickers: CEconItemPreviewDataBlock_Sticker[];
    /**
     * @generated from protobuf field: optional uint32 inventory = 13
     */
    inventory?: number;
    /**
     * @generated from protobuf field: optional uint32 origin = 14
     */
    origin?: number;
    /**
     * @generated from protobuf field: optional uint32 questid = 15
     */
    questid?: number;
    /**
     * @generated from protobuf field: optional uint32 dropreason = 16
     */
    dropreason?: number;
    /**
     * @generated from protobuf field: optional uint32 musicindex = 17
     */
    musicindex?: number;
    /**
     * @generated from protobuf field: optional int32 entindex = 18
     */
    entindex?: number;
    /**
     * @generated from protobuf field: optional uint32 petindex = 19
     */
    petindex?: number;
    /**
     * @generated from protobuf field: repeated CEconItemPreviewDataBlock.Sticker keychains = 20
     */
    keychains: CEconItemPreviewDataBlock_Sticker[];
}
/**
 * @generated from protobuf message CEconItemPreviewDataBlock.Sticker
 */
export interface CEconItemPreviewDataBlock_Sticker {
    /**
     * @generated from protobuf field: optional uint32 slot = 1
     */
    slot?: number;
    /**
     * @generated from protobuf field: optional uint32 sticker_id = 2
     */
    stickerId?: number;
    /**
     * @generated from protobuf field: optional float wear = 3
     */
    wear?: number;
    /**
     * @generated from protobuf field: optional float scale = 4
     */
    scale?: number;
    /**
     * @generated from protobuf field: optional float rotation = 5
     */
    rotation?: number;
    /**
     * @generated from protobuf field: optional uint32 tint_id = 6
     */
    tintId?: number;
    /**
     * @generated from protobuf field: optional float offset_x = 7
     */
    offsetX?: number;
    /**
     * @generated from protobuf field: optional float offset_y = 8
     */
    offsetY?: number;
    /**
     * @generated from protobuf field: optional float offset_z = 9
     */
    offsetZ?: number;
    /**
     * @generated from protobuf field: optional uint32 pattern = 10
     */
    pattern?: number;
    /**
     * @generated from protobuf field: optional uint32 highlight_reel = 11
     */
    highlightReel?: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class CEconItemPreviewDataBlock$Type extends MessageType<CEconItemPreviewDataBlock> {
    constructor() {
        super("CEconItemPreviewDataBlock", [
            { no: 1, name: "accountid", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "itemid", kind: "scalar", opt: true, T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "defindex", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "paintindex", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "rarity", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 6, name: "quality", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 7, name: "paintwear", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 8, name: "paintseed", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 9, name: "killeaterscoretype", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 10, name: "killeatervalue", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 11, name: "customname", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "stickers", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => CEconItemPreviewDataBlock_Sticker },
            { no: 13, name: "inventory", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 14, name: "origin", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 15, name: "questid", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 16, name: "dropreason", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 17, name: "musicindex", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 18, name: "entindex", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 19, name: "petindex", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 20, name: "keychains", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => CEconItemPreviewDataBlock_Sticker }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message CEconItemPreviewDataBlock
 */
export const CEconItemPreviewDataBlock = new CEconItemPreviewDataBlock$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CEconItemPreviewDataBlock_Sticker$Type extends MessageType<CEconItemPreviewDataBlock_Sticker> {
    constructor() {
        super("CEconItemPreviewDataBlock.Sticker", [
            { no: 1, name: "slot", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "sticker_id", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "wear", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 4, name: "scale", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 5, name: "rotation", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 6, name: "tint_id", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 7, name: "offset_x", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 8, name: "offset_y", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 9, name: "offset_z", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 10, name: "pattern", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 11, name: "highlight_reel", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message CEconItemPreviewDataBlock.Sticker
 */
export const CEconItemPreviewDataBlock_Sticker = new CEconItemPreviewDataBlock_Sticker$Type();
